name: Mirror Repo

on:
  schedule:
  # Run every hour
  - cron: "*/10 * * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      source_repository: 'jerinphilip/gh-workflow-multi-repo-sync'
      target_repository: 'jerinphilip/gh-workflow-mulit-repo-sync-mirror'


    steps:
      - uses: actions/checkout@v2

      - name: Push 
        run: |
          git clone -b main https://github.com/${{ env.source_repository }} source
          cd source
          git remote add mirror https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.target_repository }}
          git push mirror main
        if: github.repository == ${{ env.target_repository }}
